#!/bin/sh
# Compile Omnitext's WebAssembly binaries from source, for the F-Droid build.
#
# F-Droid builds apps from source and refuses prebuilt binaries from npm. Every .wasm FILE the
# app ships is rebuilt here from pinned upstream sources and written over the copy npm installed,
# so the build that follows packages our compile instead. The Play and web builds never run this.
#
# Some binaries are base64 inside a JavaScript file rather than a .wasm beside it; those are
# rebuilt and the string replaced (embed-wasm.py): libheif-js, @webtoon/psd, xzwasm and
# hysnappy. Nothing the app ships is a prebuilt binary any more.
#
# The Tesseract and onnxruntime engines are the binaries the app used to download instead of
# shipping; the F-Droid build now packages them (OMNITEXT_BUNDLE_TESSERACT=1 and
# OMNITEXT_BUNDLE_ONNXRUNTIME=1 in vite.config.ts), so they are rebuilt here too.
#
# Each binary pins the Emscripten version its upstream uses, which is what makes the result
# byte-identical to the npm file: the script reports IDENTICAL or differs for each one.
#
# Run after `npm ci` and before `npm run build`, from the repository root:
#   scripts/fdroid/build-wasm.sh            # every binary
#   scripts/fdroid/build-wasm.sh sqljs      # just one
#   scripts/fdroid/build-wasm.sh restore    # put the npm files back after a local run
# Needs git, python3, perl, make, patch, gcc, clang + lld + wasi-libc (wasm32 target), curl,
# unzip, pkg-config, libatomic1, node, sha3sum
# (Debian: libdigest-sha3-perl), cmake (libass, libheif, tesseract), ninja + g++ +
# protobuf-compiler + libprotobuf-dev + python3-flatbuffers + npm (onnxruntime: its WebGPU
# shader templates are generated by a node tool it installs), and for libass: ragel libtool
# libtool-bin itstool python3-ply gettext autopoint automake autoconf m4 gperf licensecheck
# gawk, and for @webtoon/psd: rustc cargo libstd-rust-dev-wasm32 binaryen libssl-dev (the
# wasm-bindgen CLI links it). Locally, run it in a clean Debian through
# scripts/fdroid/in-docker.sh, which is what F-Droid's servers look like.
set -eu

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
WORK="$ROOT/scripts/fdroid/work"
EMSDK_TAG="5.0.0" # the emsdk checkout itself; it installs any compiler version below
mkdir -p "$WORK"
cd "$ROOT"
BASE_PATH="$PATH" # each emsdk_use starts from this, so versions do not stack

# Activate one Emscripten version, installing it on first use.
emsdk_use() {
  if [ ! -d "$WORK/emsdk" ]; then
    git -c advice.detachedHead=false clone -q --depth 1 --branch "$EMSDK_TAG" https://github.com/emscripten-core/emsdk.git "$WORK/emsdk"
  fi
  (cd "$WORK/emsdk" && ./emsdk install "$1" >/dev/null && ./emsdk activate "$1" >/dev/null)
  # emsdk_env.sh cannot locate itself when sourced from plain sh, so set what it would.
  export EMSDK="$WORK/emsdk" EM_CONFIG="$WORK/emsdk/.emscripten"
  # Old toolchains build their system libraries in filesystem order, which differs per machine;
  # sorting those lists is what makes the output the same everywhere. Patching drops the cache.
  if python3 "$ROOT/scripts/fdroid/emsdk-sort-sources.py" "$EMSDK/upstream/emscripten/tools/system_libs.py"; then
    rm -rf "$EMSDK/upstream/emscripten/cache"
  fi
  PATH="$EMSDK/upstream/emscripten:$EMSDK:$(dirname "$(ls -d "$EMSDK"/node/*/bin/node | tail -1)"):$BASE_PATH"
  echo "  emcc $(emcc --version | head -1 | sed 's/.*) //')"
  # One compile alone before any parallel make. On a cold cache every concurrent emcc runs the
  # sanity check, and the one that erases the cache folder pulls it from under the others.
  mkdir -p "$WORK/warmup" && printf 'int main(void){return 0;}\n' >"$WORK/warmup/warmup.c"
  emcc "$WORK/warmup/warmup.c" -o "$WORK/warmup/warmup.js" >/dev/null
}

# Keep the npm file aside (once, under work/, never next to it: some folders ship whole),
# install ours over it, and say whether they match.
install_over() { # built-file npm-file
  orig="$WORK/npm-originals/$2"
  [ -f "$orig" ] || { mkdir -p "$(dirname "$orig")" && cp "$2" "$orig"; }
  cp "$1" "$2"
  if cmp -s "$2" "$orig"; then echo "  IDENTICAL $(basename "$2")"; else echo "  differs   $(basename "$2")"; fi
}

npm_version() { node -p "require('./node_modules/$1/package.json').version"; }

# ALAC decoder, mediaplay's build of Apple's reference sources (shipped inside the package).
build_alac() {
  echo "alac"
  emsdk_use 4.0.7
  src="$WORK/alac"
  rm -rf "$src" && cp -R node_modules/mediaplay/alac "$src" && rm -f "$src"/dist/*
  ALAC_EMCC=emcc sh "$src/build.sh" >/dev/null
  for f in alac.wasm alac.mjs; do install_over "$src/dist/$f" "node_modules/mediaplay/alac/dist/$f"; done
}

# sql.js, at the version npm installed. The app loads the browser glue with the generic wasm, so
# both builds are replaced together.
build_sqljs() {
  v="$(npm_version sql.js)"
  echo "sql.js $v"
  emsdk_use 5.0.0
  src="$WORK/sql.js"
  [ -d "$src" ] || git -c advice.detachedHead=false clone -q --depth 1 --branch "v$v" https://github.com/sql-js/sql.js.git "$src"
  make -C "$src" dist/sql-wasm.js dist/sql-wasm-browser.js >/dev/null
  for f in sql-wasm.js sql-wasm.wasm sql-wasm-browser.js sql-wasm-browser.wasm; do
    install_over "$src/dist/$f" "node_modules/sql.js/dist/$f"
  done
}

# libav.js audio decoders (AC-3, E-AC-3, DTS, TrueHD), mediaplay's configuration: see
# node_modules/mediaplay/libav/NOTICE.md. The version comes from the file names it ships.
build_libav() {
  v="$(ls node_modules/mediaplay/libav/ | sed -n 's/^libav-\(.*\)-audio\.mjs$/\1/p')"
  echo "libav.js $v"
  emsdk_use 5.0.0
  src="$WORK/libav.js"
  [ -d "$src" ] || git -c advice.detachedHead=false clone -q --depth 1 --branch "v$v" https://github.com/Yahweasel/libav.js.git "$src"
  (cd "$src/configs" && node mkconfig.js audio '["avcodec","decoder-eac3","decoder-ac3","parser-ac3","decoder-dca","parser-dca","decoder-truehd","decoder-mlp","parser-mlp"]')
  # From inside the checkout, not make -C: its Makefile installs to $(PWD)/build/inst, and -C
  # leaves PWD pointing at the caller (the library then lands outside and the link fails).
  (cd "$src" && PWD="$src" make -j"$(nproc)" build-audio) >"$WORK/libav-build.log" 2>&1 || { tail -20 "$WORK/libav-build.log"; exit 1; }
  for f in "libav-$v-audio.mjs" "libav-$v-audio.wasm.mjs" "libav-$v-audio.wasm.wasm"; do
    install_over "$src/dist/$f" "node_modules/mediaplay/libav/$f"
  done
}

# 7-Zip (Omnitext only writes .7z with it), the way 7z-wasm builds it: 7-Zip 24.09 source, its
# emscripten patch and flags, Emscripten 4.0.10. Built WITHOUT RAR: 7-Zip's RAR code carries the
# unRAR licence, which F-Droid counts as non-free. Reading RAR goes through libarchive, whose RAR
# reader is its own BSD code, so nothing is lost; the output differs from npm for that reason.
SEVENZIP_SRC="https://github.com/ip7z/7zip/releases/download/24.09/7z2409-src.tar.xz"
SEVENZIP_SHA256="49c05169f49572c1128453579af1632a952409ced028259381dac30726b6133a"
build_7zip() {
  v="$(npm_version 7z-wasm)"
  echo "7-Zip 24.09 via 7z-wasm $v (no RAR)"
  emsdk_use 4.0.10
  [ -d "$WORK/7z-wasm" ] || git -c advice.detachedHead=false clone -q --depth 1 --branch "v$v" https://github.com/use-strict/7z-wasm.git "$WORK/7z-wasm"
  tarball="$WORK/7z2409-src.tar.xz"
  [ -f "$tarball" ] || curl -sSfL -o "$tarball" "$SEVENZIP_SRC"
  echo "$SEVENZIP_SHA256  $tarball" | sha256sum -c --quiet
  src="$WORK/7zip" && rm -rf "$src" && mkdir -p "$src" && tar xJf "$tarball" -C "$src"
  # git apply copes with 7-Zip's CRLF sources (patch does not), but inside Omnitext's repository
  # it resolves paths against that repository and silently skips these: give it its own.
  (cd "$src" && git init -q && git apply --ignore-whitespace "$WORK/7z-wasm/7zz-emcc.patch")
  (
    cd "$src/CPP/7zip/Bundles/Alone2"
    # build-es6.env is in docker --env-file format (unquoted values with spaces): export by line.
    while IFS= read -r line; do [ -n "$line" ] && export "$line"; done < "$WORK/7z-wasm/build-es6.env"
    emmake make -j"$(nproc)" -f makefile.emcc DISABLE_RAR=1 >"$WORK/7zip-build.log" 2>&1 || { tail -20 "$WORK/7zip-build.log"; exit 1; }
  )
  install_over "$src/CPP/7zip/Bundles/Alone2/_o/7zz.js" node_modules/7z-wasm/7zz.es6.js
  install_over "$src/CPP/7zip/Bundles/Alone2/_o/7zz.wasm" node_modules/7z-wasm/7zz.wasm
}

# Download a source archive once and check it against the pinned checksum.
fetch() { # url sha256 -> prints the local path
  f="$WORK/dl/$(basename "$1")"
  mkdir -p "$WORK/dl"
  [ -f "$f" ] || curl -sSfL -o "$f" "$1"
  echo "$2  $f" | sha256sum -c --quiet >&2
  echo "$f"
}

# libarchive (reads 7z, RAR, xz, bz2...), following libarchive-wasm's lib/Dockerfile and
# lib/build.bash: static OpenSSL, zlib, bzip2 and xz, then libarchive, then its small C binding,
# on Emscripten 4.0.5. Installed into a prefix under work/ instead of /usr/local.
build_libarchive() {
  v="$(npm_version libarchive-wasm)"
  echo "libarchive 3.7.7 via libarchive-wasm $v"
  emsdk_use 4.0.5
  [ -d "$WORK/libarchive-wasm/.git" ] || git -c advice.detachedHead=false clone -q --depth 1 --branch "v$v" https://github.com/ofk/libarchive-wasm.git "$WORK/libarchive-wasm"
  P="$WORK/la-prefix" B="$WORK/la-build" LOG="$WORK/libarchive-build.log"
  rm -rf "$P" "$B" && mkdir -p "$P" "$B" && : > "$LOG"
  step() { "$@" >>"$LOG" 2>&1 || { tail -25 "$LOG"; exit 1; }; }

  cd "$B" && tar xf "$(fetch https://github.com/openssl/openssl/releases/download/openssl-3.4.1/openssl-3.4.1.tar.gz 002a2d6b30b58bf4bea46c43bdd96365aaf8daa6c428782aa4feee06da197df3)"
  cd openssl-3.4.1
  step emmake bash -c "./Configure no-asm no-deprecated no-dso no-ssl3 no-tests -static linux-generic32 --prefix=$P --libdir=lib"
  sed -i 's/CROSS_COMPILE=\/.*\/em/CROSS_COMPILE=/' Makefile
  step emmake make -j"$(nproc)"
  step emmake make install_sw

  cd "$B" && unzip -q "$(fetch https://github.com/madler/zlib/archive/v1.3.1.zip 50b24b47bf19e1f35d2a21ff36d2a366638cdf958219a66f30ce0861201760e6)"
  cd zlib-1.3.1 && step emconfigure ./configure --static --prefix="$P" && step emmake make -j"$(nproc)" && step emmake make install

  cd "$B" && tar xf "$(fetch https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269)"
  cd bzip2-1.0.8 && step make CC=emcc AR=emar RANLIB=emranlib libbz2.a && step make CC=emcc AR=emar RANLIB=emranlib PREFIX="$P" install

  cd "$B" && tar xf "$(fetch https://github.com/tukaani-project/xz/releases/download/v5.6.4/xz-5.6.4.tar.gz 269e3f2e512cbd3314849982014dc199a7b2148cf5c91cedc6db629acdf5e09b)"
  cd xz-5.6.4 && sed -i 's/defined(__wasm__)/0/' src/common/mythread.h
  step emconfigure ./configure --host=wasm32-unknown-emscripten --disable-assembler --enable-threads=no --enable-static=yes --disable-shared --enable-symbol-versions=no --prefix="$P"
  step emmake make -j"$(nproc)" && step emmake make install

  cd "$B" && unzip -q "$(fetch https://github.com/libarchive/libarchive/releases/download/v3.7.7/libarchive-3.7.7.zip 2fb3a5aef8e3d20b6c3f70265d04385045d4f5be098c5f969c60caaf9251b63a)"
  cd libarchive-3.7.7
  step env CPPFLAGS="-I$P/include" LDLIBS="-lz -lbz2 -lssl -lcrypto" LDFLAGS="-L$P/lib" emconfigure ./configure --host=wasm32-unknown-emscripten --prefix="$P" \
    --disable-shared --enable-static --enable-bsdtar=static --enable-bsdcat=static --enable-bsdcpio=static \
    --enable-posix-regex-lib=libc --disable-xattr --disable-acl \
    --without-lz4 --without-lzo2 --without-cng --without-nettle --without-xml2 --without-expat
  step env CPPFLAGS="-I$P/include" LDLIBS="-lz -lbz2 -lssl -lcrypto" LDFLAGS="-L$P/lib" emmake make -j"$(nproc)"
  step emmake make install

  cd "$WORK/libarchive-wasm/lib" && mkdir -p "$B/out"
  step emcc ./libarchive.c -I "$P/include" "$P/lib/libarchive.a" \
    "$P/lib/libz.a" "$P/lib/libbz2.a" "$P/lib/liblzma.a" "$P/lib/libssl.a" "$P/lib/libcrypto.a" \
    -o "$B/out/libarchive.js" \
    -s MODULARIZE=1 -s EXPORT_NAME=libarchive -s WASM=1 -s WASM_BIGINT=0 -O3 -s ALLOW_MEMORY_GROWTH=1 \
    -s EXPORTED_RUNTIME_METHODS='["cwrap"]' -s EXPORTED_FUNCTIONS=@./exported_functions.json \
    -s ERROR_ON_UNDEFINED_SYMBOLS=0
  cd "$ROOT"
  install_over "$B/out/libarchive.js" node_modules/libarchive-wasm/dist/libarchive.js
  install_over "$B/out/libarchive.wasm" node_modules/libarchive-wasm/dist/libarchive.wasm
}

# libass and its font stack (freetype, harfbuzz, fribidi, fontconfig, expat, brotli), through
# JavascriptSubtitlesOctopus at the version npm installed: its Makefile builds every dependency
# from the git submodules it pins, on Emscripten 2.0.34 (its Dockerfile's version).
build_libass() {
  v="$(npm_version @jellyfin/libass-wasm)"
  echo "libass via JavascriptSubtitlesOctopus $v"
  emsdk_use 2.0.34
  # fontconfig bakes its prefix into the wasm, so the checkout has to sit at the same absolute
  # path everywhere or the output differs between machines (F-Droid builds under /home/vagrant).
  src="${LIBASS_BUILD_DIR:-/tmp/omnitext-libass}"
  [ -d "$src" ] || git -c advice.detachedHead=false clone -q --recurse-submodules --shallow-submodules --depth 1 --branch "v$v" https://github.com/jellyfin/JavascriptSubtitlesOctopus.git "$src"
  # fontconfig's autogen.sh reads the version off `libtoolize --version` with a regex that breaks
  # on Debian 13's "2.5.4 Debian-2.5.4-4" and then claims libtool is missing. It honours
  # LIBTOOLIZE, so point that at a wrapper that drops the Debian suffix from the version line.
  mkdir -p "$WORK/bin"
  printf '%s\n' '#!/bin/sh' \
    'if [ "${1:-}" = --version ]; then libtoolize --version | sed "1s/ Debian-[^ ]*\$//"; else exec libtoolize "$@"; fi' \
    > "$WORK/bin/libtoolize-plain"
  chmod +x "$WORK/bin/libtoolize-plain"
  export LIBTOOLIZE="$WORK/bin/libtoolize-plain"
  # Libraries first, in parallel; then the worker serially, as upstream builds everything: its
  # phony all-src step races both the libraries and the generated SubOctpInterface.js under -j.
  # Only the worker, because the full
  # `dist` also regenerates the licence notice, whose lint fails on Debian's newer licensecheck,
  # and the app keeps npm's COPYRIGHT anyway.
  (cd "$src" && make -j"$(nproc)" "$src/dist/libraries/lib/libass.a" && make dist/js/subtitles-octopus-worker.js) >"$WORK/libass-build.log" 2>&1 || { tail -25 "$WORK/libass-build.log"; exit 1; }
  for f in subtitles-octopus-worker.js subtitles-octopus-worker.wasm; do
    install_over "$src/dist/js/$f" "node_modules/@jellyfin/libass-wasm/dist/js/$f"
  done
}

# Put the npm files back (after a local run: a Play or web build must not pick up these).
# Snappy, the one Parquet codec that is WebAssembly (hysnappy, reached through
# hyparquet-compressors). Plain clang targeting wasm32, no Emscripten, as upstream's
# Makefile does it; the binary lives base64 inside the JS, so that string is what we replace.
build_hysnappy() {
  v="$(npm_version hysnappy)"
  echo "hysnappy $v"
  src="$WORK/hysnappy"
  [ -d "$src" ] || git -c advice.detachedHead=false clone -q --depth 1 --branch "v$v" https://github.com/hyparam/hysnappy.git "$src"
  for part in uncompress compress; do
    clang --target=wasm32 -O3 -nostdlib -Wl,--export-all -Wl,--no-entry \
      -o "$src/$part.wasm" "$src/c/$part.c"
    python3 "$ROOT/scripts/fdroid/embed-wasm.py" "$src/$part.wasm" \
      "node_modules/hysnappy/js/$part.js" "$WORK/hysnappy-$part.js"
    install_over "$WORK/hysnappy-$part.js" "node_modules/hysnappy/js/$part.js"
  done
}

# xz decoding for a lone .xz file (xzwasm). Upstream has no tags, so the commit is pinned
# here; its submodules (xz-embedded, walloc) are pinned by that commit in turn. Built with
# Debian's clang against its wasi headers, which is what upstream's WASI SDK provides.
XZWASM_COMMIT="75a7519c7c38fe641a9fa9809db1378fe339ac5c"
build_xzwasm() {
  echo "xzwasm $(npm_version xzwasm)"
  src="$WORK/xzwasm"
  if [ ! -d "$src" ]; then
    git clone -q https://github.com/SteveSanderson/xzwasm.git "$src"
    (cd "$src" && git -c advice.detachedHead=false checkout -q "$XZWASM_COMMIT" && git submodule update -q --init --recursive)
  fi
  xzlib="$src/module/xz-embedded/linux/lib/xz"
  clang --target=wasm32 -DNDEBUG -Os -s -nostdlib -Wl,--no-entry \
    -isystem /usr/include/wasm32-wasi \
    -DXZ_DEC_CONCATENATED -DXZ_USE_CRC64 \
    -Wl,--export=create_context -Wl,--export=destroy_context \
    -Wl,--export=supply_input -Wl,--export=get_next_output \
    -o "$src/xzwasm.wasm" \
    -I"$src/module/xz-embedded/userspace/" -I"$src/module/xz-embedded/linux/include/linux/" \
    "$src/module/walloc/walloc.c" "$src"/src/native/*.c \
    "$xzlib/xz_crc32.c" "$xzlib/xz_crc64.c" "$xzlib/xz_dec_stream.c" "$xzlib/xz_dec_lzma2.c"
  # The package ships the same binary in both the plain and the minified bundle.
  for f in xzwasm.js xzwasm.min.js; do
    python3 "$ROOT/scripts/fdroid/embed-wasm.py" "$src/xzwasm.wasm" \
      "node_modules/xzwasm/dist/package/$f" "$WORK/xzwasm-$f"
    install_over "$WORK/xzwasm-$f" "node_modules/xzwasm/dist/package/$f"
  done
}

# The PSD pixel decoder of @webtoon/psd: Rust compiled to wasm32 with wasm-bindgen, then
# wasm-opt, the way its wasm-pack build does it. The wasm-bindgen CLI is built from source at
# the version the crate's Cargo.lock pins, because the glue JS the package ships expects that
# exact ABI; the binary lives base64 inside dist/index.js, so that string is what we replace.
build_psd() {
  v="$(npm_version @webtoon/psd)"
  echo "@webtoon/psd $v"
  src="$WORK/webtoon-psd"
  [ -d "$src" ] || git -c advice.detachedHead=false clone -q --depth 1 --branch "$v" https://github.com/webtoon/psd.git "$src"
  d="$src/packages/decoder"
  wbg="$(sed -n '/^name = "wasm-bindgen"$/{n;s/version = "\(.*\)"/\1/p;}' "$d/Cargo.lock")"
  echo "  wasm-bindgen $wbg, $(rustc --version | cut -d' ' -f1-2)"
  export CARGO_HOME="$WORK/cargo"
  [ -x "$WORK/wbg/bin/wasm-bindgen" ] || cargo install -q --locked --version "$wbg" wasm-bindgen-cli --root "$WORK/wbg"
  # Debian's rustc has no rust-lld, the default wasm32 linker; lld's wasm-ld is the same thing.
  (cd "$d" && RUSTFLAGS="-Clinker=wasm-ld" cargo build -q --release --locked --target wasm32-unknown-unknown)
  "$WORK/wbg/bin/wasm-bindgen" --out-dir "$WORK/psd-pkg" --out-name webtoon_psd_decoder \
    --target bundler "$d/target/wasm32-unknown-unknown/release/webtoon_psd_decoder.wasm"
  wasm-opt -O -o "$WORK/psd-pkg/psd.wasm" "$WORK/psd-pkg/webtoon_psd_decoder_bg.wasm"
  python3 "$ROOT/scripts/fdroid/embed-wasm.py" "$WORK/psd-pkg/psd.wasm" \
    node_modules/@webtoon/psd/dist/index.js "$WORK/psd-index.js"
  install_over "$WORK/psd-index.js" node_modules/@webtoon/psd/dist/index.js
}

# HEIC/HEIF decoding: libheif with libde265 for the HEVC bitstream, the way libheif-js gets it.
# That package ships a binary built by catdad-experiments/libheif-emscripten, which pins libheif
# by git submodule and runs its build-emscripten.sh on Emscripten 3.1.61 with the wasm target and
# DYNAMIC_EXECUTION off. Decoder only: no AOM and no x265, so nothing non-free is linked in.
# The binary lives base64 inside the bundle the app imports, so that string is what we replace.
LIBHEIF_COMMIT="ac1cb05c39008f01525c991ff8b88f84ddf70fd2" # libheif v1.23.2, as libheif-emscripten v1.23.2 pins it
LIBDE265_VERSION="1.0.15"
LIBDE265_SHA256="00251986c29d34d3af7117ed05874950c875dd9292d016be29d3b3762666511d"
build_libheif() {
  echo "libheif 1.23.2 + libde265 $LIBDE265_VERSION via libheif-js $(npm_version libheif-js)"
  emsdk_use 3.1.61
  # Outside the repository: libde265's configure runs the test binaries it compiles, and node
  # refuses them under our package.json ("type": "module"). Fixed path, as libass has, so the
  # build is the same everywhere.
  src="${LIBHEIF_BUILD_DIR:-/tmp/omnitext-libheif}"
  if [ ! -d "$src" ]; then
    git clone -q https://github.com/strukturag/libheif.git "$src"
    (cd "$src" && git -c advice.detachedHead=false checkout -q "$LIBHEIF_COMMIT")
  fi
  # build-emscripten.sh fetches libde265 itself unless the tarball is already in its directory.
  cp "$(fetch "https://github.com/strukturag/libde265/releases/download/v$LIBDE265_VERSION/libde265-$LIBDE265_VERSION.tar.gz" "$LIBDE265_SHA256")" "$src/libde265-$LIBDE265_VERSION.tar.gz"
  # USE_TYPESCRIPT=0 only skips the .d.ts emcc would write after the binary (it wants tsc for
  # that, and the package's types come from npm anyway); the wasm is the same either way.
  (cd "$src" && USE_WASM=1 USE_UNSAFE_EVAL=0 USE_TYPESCRIPT=0 LIBDE265_VERSION="$LIBDE265_VERSION" \
    ./build-emscripten.sh .) >"$WORK/libheif-build.log" 2>&1 || { tail -25 "$WORK/libheif-build.log"; exit 1; }
  install_over "$src/libheif.wasm" node_modules/libheif-js/libheif-wasm/libheif.wasm
  # The app imports the bundle; the package ships it as CommonJS and as ESM, same binary in both.
  for f in libheif-bundle.js libheif-bundle.mjs; do
    python3 "$ROOT/scripts/fdroid/embed-wasm.py" "$src/libheif.wasm" \
      "node_modules/libheif-js/libheif-wasm/$f" "$WORK/libheif-$f"
    install_over "$WORK/libheif-$f" "node_modules/libheif-js/libheif-wasm/$f"
  done
}

# Tesseract (OCR), the way tesseract.js-core builds it: its nine pinned submodules (zlib, libtiff,
# openlibm, giflib, libpng, libjpeg, libwebp, leptonica and Balearica's tesseract fork) through its
# own build-scripts, on Emscripten 3.1.38 (its build-with-docker.sh pin; 4.x rejects the
# wasm32-unknown-unknown target openlibm's Makefile passes). Only the SIMD + LSTM-only variant:
# that is the one the app asks for (createWorker with OEM 1, with SIMD), and the only one it ships.
build_tesseract() {
  v="$(npm_version tesseract.js-core)"
  echo "tesseract.js-core $v (simd, LSTM only)"
  emsdk_use 3.1.38
  src="$WORK/tesseract.js-core"
  if [ ! -d "$src" ]; then
    git -c advice.detachedHead=false clone -q --depth 1 --branch "v$v" https://github.com/naptha/tesseract.js-core.git "$src"
    # Upstream pins its tesseract fork through an ssh URL, which a build machine has no key for.
    (cd "$src" && git -c url."https://github.com/".insteadOf="git@github.com:" submodule update -q --init --depth 1)
    # The checkout ships the built cores too; drop them so only our compile can be installed.
    rm -f "$src"/tesseract-core*
    # build.sh builds four variants; BUILD_SINGLE keeps the first, which this points at ours.
    sed -i 's/^BUILD_SINGLE=0/BUILD_SINGLE=1/' "$src/build-scripts/var.sh"
    sed -i 's/ -D HAVE_SSE4_1=1$/ -D HAVE_SSE4_1=1 -D DISABLED_LEGACY_ENGINE=1/' "$src/build-scripts/build-tesseract.sh"
  fi
  (cd "$src" && bash ./build.sh) >"$WORK/tesseract-build.log" 2>&1 || { tail -25 "$WORK/tesseract-build.log"; exit 1; }
  # .js + .wasm as a pair, and .wasm.js with the binary inside it: that is the one the app loads.
  for f in tesseract-core-simd-lstm.js tesseract-core-simd-lstm.wasm tesseract-core-simd-lstm.wasm.js; do
    install_over "$src/$f" "node_modules/tesseract.js-core/$f"
  done
}

# onnxruntime, the engine transformers.js downloads for translation, the writing assist and
# transcription; the F-Droid build packages it (OMNITEXT_BUNDLE_ONNXRUNTIME=1 in vite.config.ts).
# npm ships a pre-release snapshot of 1.26.0 taken from an untagged commit, so the release that
# commit became is pinned instead. One variant, ort-wasm-simd-threaded.asyncify: that is the pair
# transformers.js names for every browser but Safari, and Safari is not a build target here.
# Built with upstream's own flags for that artifact (web.yml's wasm_Release job, the
# "WebGPU experimental" step, reduced types and all), on the Emscripten its emsdk submodule pins.
ONNXRUNTIME_TAG="v1.26.0"
build_onnxruntime() {
  v="$(npm_version onnxruntime-web)"
  echo "onnxruntime-web $v, built from $ONNXRUNTIME_TAG (simd + threads + webgpu/webnn, asyncify)"
  src="$WORK/onnxruntime"
  if [ ! -d "$src" ]; then
    git -c advice.detachedHead=false clone -q --depth 1 --branch "$ONNXRUNTIME_TAG" https://github.com/microsoft/onnxruntime.git "$src"
    (cd "$src" && git submodule update -q --init --depth 1 cmake/external/emsdk cmake/external/onnx)
    # Its post-build script uses require(), and the checkout sits under a repository whose
    # package.json says "type": "module"; this stops node reading that one.
    echo '{ "type": "commonjs" }' >"$src/package.json"
  fi
  # Debian's protobuf-compiler is the version deps.txt pins, and taking it stops cmake fetching
  # an x86_64 protoc; NODE_EXECUTABLE because the Emscripten toolchain hides the host node.
  (cd "$src" && EMSDK_NODE=/usr/bin/node python3 tools/ci_build/build.py \
    --build_dir "$src/BUILD" --config Release --skip_submodule_sync --parallel \
    --build_wasm --enable_wasm_simd --enable_wasm_threads \
    --use_webgpu --use_webnn --target onnxruntime_webassembly \
    --skip_tests --disable_rtti --enable_wasm_api_exception_catching \
    --disable_ml_ops --disable_generation_ops \
    --disable_types string float4 float8 optional sparsetensor \
    --include_ops_by_config onnxruntime/wasm/reduced_types.config \
    --enable_reduced_operator_type_support \
    --allow_running_as_root --path_to_protoc_exe /usr/bin/protoc \
    --cmake_extra_defines NODE_EXECUTABLE=/usr/bin/node) >"$WORK/onnxruntime-build.log" 2>&1 ||
    { tail -25 "$WORK/onnxruntime-build.log"; exit 1; }
  for f in ort-wasm-simd-threaded.asyncify.mjs ort-wasm-simd-threaded.asyncify.wasm; do
    install_over "$src/BUILD/Release/$f" "node_modules/onnxruntime-web/dist/$f"
  done
}

build_restore() {
  echo "restore npm binaries"
  [ -d "$WORK/npm-originals" ] || return 0
  (cd "$WORK/npm-originals" && find . -type f) | while read -r f; do cp "$WORK/npm-originals/$f" "$ROOT/$f"; echo "  $f"; done
}

ALL="alac sqljs libav 7zip libarchive libass hysnappy xzwasm psd libheif tesseract onnxruntime"
for target in ${*:-$ALL}; do
  "build_$target"
done
