import { strToU8, zipSync } from "fflate";

// Minimal valid blank documents for the binary formats, so they can be created from the
// New dialog (they cannot be made from empty text the way text formats can). Office/ODF
// files are tiny zips; spreadsheets and PDF are generated by their libraries on demand.

const DOCX_CT =
  '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
  '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">' +
  '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>' +
  '<Default Extension="xml" ContentType="application/xml"/>' +
  '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>' +
  "</Types>";
const DOCX_RELS =
  '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
  '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' +
  '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>' +
  "</Relationships>";
const DOCX_DOCRELS =
  '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
  '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"></Relationships>';

export type Paper = "a3" | "a4" | "a5" | "b4" | "b5" | "letter" | "legal" | "tabloid" | "executive";
export type Orientation = "portrait" | "landscape";
/** The page sizes the New dialog offers, in display order. */
export const PAPER_SIZES = ["a4", "a3", "a5", "b4", "b5", "letter", "legal", "tabloid", "executive"] as const;

// Page size in twips (1/1440in). ISO/JIS sizes are mm, the US sizes are inches.
const DOCX_PGSZ: Record<Paper, { w: number; h: number }> = {
  a3: { w: 16838, h: 23811 }, // 297x420mm
  a4: { w: 11906, h: 16838 }, // 210x297mm
  a5: { w: 8391, h: 11906 }, // 148x210mm
  b4: { w: 14570, h: 20636 }, // 257x364mm (JIS)
  b5: { w: 10318, h: 14570 }, // 182x257mm (JIS)
  letter: { w: 12240, h: 15840 }, // 8.5x11in
  legal: { w: 12240, h: 20160 }, // 8.5x14in
  tabloid: { w: 15840, h: 24480 }, // 11x17in
  executive: { w: 10440, h: 15120 }, // 7.25x10.5in
};
const docxDoc = (paper: Paper, orient: Orientation): string => {
  let { w, h } = DOCX_PGSZ[paper];
  const landscape = orient === "landscape";
  if (landscape) [w, h] = [h, w];
  return (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
    '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>' +
    "<w:p/>" +
    `<w:sectPr><w:pgSz w:w="${w}" w:h="${h}"${landscape ? ' w:orient="landscape"' : ""}/><w:pgMar w:top="1418" w:right="1418" w:bottom="1418" w:left="1418"/></w:sectPr>` +
    "</w:body></w:document>"
  );
};

function blankDocx(paper: Paper, orient: Orientation): Uint8Array {
  return zipSync({
    "[Content_Types].xml": strToU8(DOCX_CT),
    "_rels/.rels": strToU8(DOCX_RELS),
    "word/document.xml": strToU8(docxDoc(paper, orient)),
    "word/_rels/document.xml.rels": strToU8(DOCX_DOCRELS),
  });
}

const ODT_CONTENT =
  '<?xml version="1.0" encoding="UTF-8"?>' +
  '<office:document-content xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" ' +
  'xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" office:version="1.2">' +
  "<office:body><office:text><text:p/></office:text></office:body></office:document-content>";
const ODT_PAGE: Record<Paper, { w: string; h: string }> = {
  a3: { w: "29.7cm", h: "42cm" },
  a4: { w: "21cm", h: "29.7cm" },
  a5: { w: "14.8cm", h: "21cm" },
  b4: { w: "25.7cm", h: "36.4cm" },
  b5: { w: "18.2cm", h: "25.7cm" },
  letter: { w: "8.5in", h: "11in" },
  legal: { w: "8.5in", h: "14in" },
  tabloid: { w: "11in", h: "17in" },
  executive: { w: "7.25in", h: "10.5in" },
};
const odtStyles = (paper: Paper, orient: Orientation): string => {
  let { w, h } = ODT_PAGE[paper];
  if (orient === "landscape") [w, h] = [h, w];
  return (
    '<?xml version="1.0" encoding="UTF-8"?>' +
    '<office:document-styles xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" ' +
    'xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0" ' +
    'xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" office:version="1.2">' +
    '<office:automatic-styles><style:page-layout style:name="pm1">' +
    `<style:page-layout-properties fo:page-width="${w}" fo:page-height="${h}" style:print-orientation="${orient}" fo:margin-top="2cm" fo:margin-bottom="2cm" fo:margin-left="2cm" fo:margin-right="2cm"/>` +
    "</style:page-layout></office:automatic-styles>" +
    '<office:master-styles><style:master-page style:name="Standard" style:page-layout-name="pm1"/></office:master-styles>' +
    "</office:document-styles>"
  );
};
const ODT_MANIFEST =
  '<?xml version="1.0" encoding="UTF-8"?>' +
  '<manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" manifest:version="1.2">' +
  '<manifest:file-entry manifest:full-path="/" manifest:version="1.2" manifest:media-type="application/vnd.oasis.opendocument.text"/>' +
  '<manifest:file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/>' +
  '<manifest:file-entry manifest:full-path="styles.xml" manifest:media-type="text/xml"/>' +
  "</manifest:manifest>";

function blankOdt(paper: Paper, orient: Orientation): Uint8Array {
  return zipSync({
    mimetype: [strToU8("application/vnd.oasis.opendocument.text"), { level: 0 }],
    "content.xml": strToU8(ODT_CONTENT),
    "styles.xml": strToU8(odtStyles(paper, orient)),
    "META-INF/manifest.xml": strToU8(ODT_MANIFEST),
  });
}

async function blankSheet(bookType: "xlsx" | "ods" | "xls"): Promise<Uint8Array> {
  const XLSX = await import("xlsx");
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([[""]]), "Sheet1");
  return new Uint8Array(XLSX.write(wb, { bookType, type: "array" }) as ArrayBuffer);
}

async function blankPdf(): Promise<Uint8Array> {
  const { PDFDocument } = await import("pdf-lib");
  const doc = await PDFDocument.create();
  doc.addPage();
  return doc.save();
}

/** Format ids that can be created blank from the New dialog despite being binary. */
export const BLANK_BINARY_FORMATS = ["docx", "odt", "xlsx", "ods", "xls", "pdf"] as const;

/** Formats whose blank template honors a paper size (the New dialog offers the choice). */
export const PAPER_FORMATS = ["docx", "odt"] as const;

/** Generate the bytes of a blank document for a binary format, or null if unsupported. */
export async function blankTemplate(formatId: string, paper: Paper = "a4", orient: Orientation = "portrait"): Promise<Uint8Array | null> {
  switch (formatId) {
    case "docx": return blankDocx(paper, orient);
    case "odt": return blankOdt(paper, orient);
    case "xlsx": return blankSheet("xlsx");
    case "ods": return blankSheet("ods");
    case "xls": return blankSheet("xls");
    case "pdf": return blankPdf();
    default: return null;
  }
}
