// Generates dist/sw.js after `vite build` (postbuild hook). The service worker
// precaches the whole dist so the app works offline and lazy chunks from a
// previous deploy never 404 mid-session: an open page keeps its own cache until
// the new worker activates, and activation only happens once no old page is left.
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const dist = fileURLToPath(new URL("../dist", import.meta.url));

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
}

const files = walk(dist)
  .map((p) => relative(dist, p).split("\\").join("/"))
  .filter((p) => p !== "sw.js" && !p.endsWith(".DS_Store"))
  .sort();

// The cache version is a digest of every file's content, so any change in the
// deploy (including unhashed files like index.html or svgedit assets) produces
// a new cache and an update cycle; identical rebuilds do not.
const h = createHash("sha256");
for (const f of files) {
  h.update(f);
  h.update(readFileSync(join(dist, f)));
}
const version = h.digest("hex").slice(0, 12);

// What a boot cannot do without: the shell and the scripts and stylesheets it names.
// Everything else (lazy editor chunks, fonts, wasm) can arrive later from the network,
// but without these the page comes up blank, so the install refuses to go live unless
// they are all cached. Read from index.html rather than listed by hand: a build that
// renames its entry chunk must not quietly drop it out of the set that matters.
const indexHtml = readFileSync(join(dist, "index.html"), "utf8");
const core = ["index.html", ...new Set(
  [...indexHtml.matchAll(/(?:href|src)="\.\/((?:assets\/)[^"]+\.(?:js|css))"/g)].map((m) => m[1]),
)];
const missing = core.filter((f) => f !== "index.html" && !files.includes(f));
if (missing.length) throw new Error(`index.html references files not in dist: ${missing.join(", ")}`);
// If the bundler ever changes how it links the entry, the pattern above quietly matches
// nothing and the install goes back to accepting an unbootable cache. Fail the build.
if (!core.some((f) => f.endsWith(".js")) || !core.some((f) => f.endsWith(".css"))) {
  throw new Error("index.html: no entry script and stylesheet found, so the core set would not cover a boot");
}

const sw = `// Generated by scripts/gen-sw.mjs at build time; do not edit.
const CACHE = "omnitext-${version}";
// The shell and its entry chunks: an install that cannot cache these fails on purpose.
const CORE = ${JSON.stringify(core)};
// Holds a single file handed to the app via the OS share sheet, between the POST the
// browser makes to share_target.action and the app reading it after the redirect.
const SHARE_CACHE = "omnitext-share";
const ASSETS = ${JSON.stringify(files)};

// Store a clean synthetic response. cache.put would keep the network headers
// on an already-decoded body, and stale Content-Encoding or Vary: Origin
// headers make the browser reject the entry for crossorigin-attributed
// stylesheet/script requests (Vite emits all of those with crossorigin).
async function sanitize(res) {
  const body = await res.blob();
  const headers = {};
  const ct = res.headers.get("Content-Type");
  if (ct) headers["Content-Type"] = ct;
  return new Response(body, { status: 200, headers });
}

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const oldKeys = (await caches.keys()).filter((k) => k !== CACHE);
    const old = oldKeys.length ? await caches.open(oldKeys[oldKeys.length - 1]) : null;
    // The shell first, and this part must succeed. Installing during a bad window (a
    // deploy still propagating, a dropped connection) used to leave a worker that had
    // cached nothing, report success, and then delete the previous cache on activate,
    // taking working offline support with it. Throwing here discards this worker
    // instead, so the one already serving the app stays in charge and tries again.
    await Promise.all(CORE.map(async (url) => {
      const res = await fetch(url, { cache: "no-cache" });
      if (!res.ok) throw new Error("core asset " + url + " -> " + res.status);
      await cache.put(url, await sanitize(res));
    }));
    await Promise.allSettled(ASSETS.filter((u) => !CORE.includes(u)).map(async (url) => {
      // Vite content-hashes everything under assets/, so an old cache entry
      // with the same name is byte-identical: copy it instead of refetching.
      if (old && url.startsWith("assets/")) {
        const hit = await old.match(url);
        if (hit) { await cache.put(url, hit); return; }
      }
      const res = await fetch(url, { cache: "no-cache" });
      // A rapid re-deploy can delete assets this build listed. Skip a missing one
      // rather than failing the whole install, which would leave the OLD worker stuck
      // serving now-404 chunks. Anything skipped is fetched from network on demand.
      if (!res.ok) return;
      await cache.put(url, await sanitize(res));
    }));
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    // Drop stale asset caches but keep a pending shared file across the update cycle.
    for (const k of await caches.keys()) if (k !== CACHE && k !== SHARE_CACHE) await caches.delete(k);
    await self.clients.claim();
    // Any window still showing the previous build is now holding chunk URLs this cache
    // does not have. Tell it, so it can say so rather than fail on the next lazy import.
    for (const client of await self.clients.matchAll({ type: "window" })) {
      client.postMessage({ type: "omnitext-activated" });
    }
  })());
});

// "Update now" from the settings dialog. Waiting for every window to close is the safe
// default; this is the user overriding it, and the page that asks reloads immediately.
self.addEventListener("message", (event) => {
  if (event.data === "omnitext-skip-waiting") self.skipWaiting();
});

// Web Share Target: the OS POSTs the shared file(s) here. Stash the first file in a
// cache and redirect to the app with a marker; the app reads and opens it on load.
async function handleShare(req) {
  try {
    const form = await req.formData();
    const file = form.get("files");
    if (file && typeof file === "object" && file.name) {
      const cache = await caches.open(SHARE_CACHE);
      await cache.put("shared-file", new Response(file, {
        headers: {
          "Content-Type": file.type || "application/octet-stream",
          "X-Filename": encodeURIComponent(file.name),
        },
      }));
    }
  } catch (e) {
    /* a malformed share just opens the app empty */
  }
  return Response.redirect(new URL("./?share-target=1", self.registration.scope).href, 303);
}

self.addEventListener("fetch", (event) => {
  const req = event.request;
  const shareUrl = new URL(req.url);
  if (req.method === "POST" && shareUrl.pathname.endsWith("/share-target")) {
    event.respondWith(handleShare(req));
    return;
  }
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (req.mode === "navigate") {
    // Cache-first for the shell, deliberately. A cache holds one deploy's index.html
    // together with the exact chunks that index.html names, so booting from it is
    // always self-consistent. Going to the network hands back a fresh index.html
    // naming chunks this worker never cached, and if the network cannot serve them
    // right then (a deploy still propagating, a flaky moment) the page comes up with
    // no stylesheet and no editor. A new deploy arrives through the worker's own
    // update cycle instead, which swaps the shell and its chunks together.
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const shell = (await cache.match(req, { ignoreSearch: true })) || (await cache.match("index.html"));
      if (shell) return shell;
      try {
        return await fetch(req); // first visit: nothing precached yet
      } catch {
        return Response.error();
      }
    })());
    return;
  }
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, { ignoreSearch: true });
    if (hit) return hit;
    const res = await fetch(req);
    if (res.ok && res.type === "basic") await cache.put(req, await sanitize(res.clone()));
    return res;
  })());
});
`;

writeFileSync(join(dist, "sw.js"), sw);
console.log(`sw.js: ${files.length} assets precached, cache omnitext-${version}`);
