// Generates dist/sw.js after `vite build` (postbuild hook). The service worker
// precaches the whole dist so the app works offline and lazy chunks from a
// previous deploy never 404 mid-session: an open page keeps its own cache until
// the new worker activates, and activation only happens once no old page is left.
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const dist = fileURLToPath(new URL("../dist", import.meta.url));

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
}

const files = walk(dist)
  .map((p) => relative(dist, p).split("\\").join("/"))
  .filter((p) => p !== "sw.js" && !p.endsWith(".DS_Store"))
  .sort();

// The cache version is a digest of every file's content, so any change in the
// deploy (including unhashed files like index.html or svgedit assets) produces
// a new cache and an update cycle; identical rebuilds do not.
const h = createHash("sha256");
for (const f of files) {
  h.update(f);
  h.update(readFileSync(join(dist, f)));
}
const version = h.digest("hex").slice(0, 12);

const sw = `// Generated by scripts/gen-sw.mjs at build time; do not edit.
const CACHE = "omnitext-${version}";
// Holds a single file handed to the app via the OS share sheet, between the POST the
// browser makes to share_target.action and the app reading it after the redirect.
const SHARE_CACHE = "omnitext-share";
const ASSETS = ${JSON.stringify(files)};

// Store a clean synthetic response. cache.put would keep the network headers
// on an already-decoded body, and stale Content-Encoding or Vary: Origin
// headers make the browser reject the entry for crossorigin-attributed
// stylesheet/script requests (Vite emits all of those with crossorigin).
async function sanitize(res) {
  const body = await res.blob();
  const headers = {};
  const ct = res.headers.get("Content-Type");
  if (ct) headers["Content-Type"] = ct;
  return new Response(body, { status: 200, headers });
}

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const oldKeys = (await caches.keys()).filter((k) => k !== CACHE);
    const old = oldKeys.length ? await caches.open(oldKeys[oldKeys.length - 1]) : null;
    await Promise.allSettled(ASSETS.map(async (url) => {
      // Vite content-hashes everything under assets/, so an old cache entry
      // with the same name is byte-identical: copy it instead of refetching.
      if (old && url.startsWith("assets/")) {
        const hit = await old.match(url);
        if (hit) { await cache.put(url, hit); return; }
      }
      const res = await fetch(url, { cache: "no-cache" });
      // A rapid re-deploy can delete assets this build listed. Skip a missing one
      // rather than failing the whole install, which would leave the OLD worker stuck
      // serving now-404 chunks. Anything skipped is fetched from network on demand.
      if (!res.ok) return;
      await cache.put(url, await sanitize(res));
    }));
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    // Drop stale asset caches but keep a pending shared file across the update cycle.
    for (const k of await caches.keys()) if (k !== CACHE && k !== SHARE_CACHE) await caches.delete(k);
    await self.clients.claim();
  })());
});

// Web Share Target: the OS POSTs the shared file(s) here. Stash the first file in a
// cache and redirect to the app with a marker; the app reads and opens it on load.
async function handleShare(req) {
  try {
    const form = await req.formData();
    const file = form.get("files");
    if (file && typeof file === "object" && file.name) {
      const cache = await caches.open(SHARE_CACHE);
      await cache.put("shared-file", new Response(file, {
        headers: {
          "Content-Type": file.type || "application/octet-stream",
          "X-Filename": encodeURIComponent(file.name),
        },
      }));
    }
  } catch (e) {
    /* a malformed share just opens the app empty */
  }
  return Response.redirect(new URL("./?share-target=1", self.registration.scope).href, 303);
}

self.addEventListener("fetch", (event) => {
  const req = event.request;
  const shareUrl = new URL(req.url);
  if (req.method === "POST" && shareUrl.pathname.endsWith("/share-target")) {
    event.respondWith(handleShare(req));
    return;
  }
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (req.mode === "navigate") {
    // Network-first so a plain reload picks up new deploys. Never cache the
    // response: a newer index.html in this cache would reference chunks the
    // cache does not hold. The precached copy serves offline.
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      try {
        return await fetch(req);
      } catch {
        return (await cache.match(req, { ignoreSearch: true }))
          || (await cache.match("index.html"))
          || Response.error();
      }
    })());
    return;
  }
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, { ignoreSearch: true });
    if (hit) return hit;
    const res = await fetch(req);
    if (res.ok && res.type === "basic") await cache.put(req, await sanitize(res.clone()));
    return res;
  })());
});
`;

writeFileSync(join(dist, "sw.js"), sw);
console.log(`sw.js: ${files.length} assets precached, cache omnitext-${version}`);
